name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]  # Runs on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Uses latest Ubuntu runner
    
    steps:
    # Checkout your code
    - uses: actions/checkout@v4
    
    # Set up Node.js 20.18.0 (matches your local version)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.18.0'  # Explicitly using your version
        cache: 'npm'  # Optional: caches node_modules for faster builds
    
    # Install dependencies
    - name: Install dependencies
      run: npm ci  # Uses package-lock.json for deterministic installs
    
    # Build your Angular project
    - name: Build
      run: |
        npm run build -- --configuration production
        ls -R dist/  # Lists built files for debugging
    
    # Deploy to GitHub Pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/portfolio  # Adjust if your dist folder is different
        keep_files: false
        enable_jekyll: false  # Important for SPAs like Angular